### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [datamllab/pyodds#12]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.0rc1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pyodds -w /tmp/ext pyodds==1.0.0rc1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pyodds==1.0.0rc1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/987/8cf3b9087dafd/pyodds-1.0.0rc1.tar.gz (37 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-kvsisbl_/pyodds/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-kvsisbl_/pyodds/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-kvsisbl_/pyodds/pip-egg-info
         cwd: /tmp/pip-wheel-kvsisbl_/pyodds/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-kvsisbl_/pyodds/setup.py", line 8, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
I can't autofix because it depends on a missing version of tensorflow.
